#!/usr/bin/env python3
"""Small, workflow-independent STR genotype caller.

Authorship and AI-use disclosure
-------------------------------
The STR calling algorithm, scientific model, thresholds, and implementation were
written by Tim Roane. After the implementation was complete, AI tools were used
to review code structure and readability and to help clarify comments and
documentation. AI was not used to originate the analytical model or calling
logic. Final technical decisions and review remained with the author.

The caller treats each STR locus as a set of read-count peaks. It models the
expected asymmetric stutter generated by the dominant allele, subtracts that
signal, then asks whether any residual peak has enough evidence to represent a
second allele. A final confidence score reports how much corrected signal is
explained by the selected genotype.

The core functions are intentionally independent of Snakemake, file layout,
and locus-specific production exceptions so the algorithm can be tested and
reused on its own.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Mapping

import pandas as pd


@dataclass(frozen=True, slots=True)
class CallerParameters:
    """Calibration and QC parameters for one STR calling model."""

    min_allele_reads: int = 20
    min_locus_reads: int = 100
    min_confidence: float = 70.0
    backward_stutter: float = 0.40
    forward_stutter: float = 0.10

    def candidate_fraction(self, offset: int) -> float:
        """Minimum residual fraction required for a second-allele candidate.

        Thresholds are relative to the dominant peak after stutter correction.
        Positive offsets become progressively less stringent because forward
        stutter decays rapidly; negative offsets remain more conservative near
        the dominant allele where backward stutter is strongest.
        """
        near_peak = {
            -4: 0.30,
            -3: 0.50,
            -2: 0.60,
            -1: 0.80,
             1: 0.30,
             2: 0.20,
             3: 0.10,
        }
        if offset in near_peak:
            return near_peak[offset]
        return 0.05 if offset > 3 else 0.10


@dataclass(frozen=True, slots=True)
class GenotypeCall:
    locus: str
    genotype: str
    confidence: float
    status: str
    primary_repeat: float | None
    secondary_repeat: float | None
    raw_depth: int
    corrected_depth: int


@dataclass(frozen=True, slots=True)
class Peak:
    repeat: float
    reads: int
    allele: str


@dataclass(frozen=True, slots=True)
class CorrectedPeak:
    repeat: float
    allele: str
    raw_reads: int
    corrected_reads: int
    selected: bool = False


def stutter_fraction(offset: float, params: CallerParameters) -> float:
    """Expected fraction of a parent peak appearing at an STR offset.

    Stutter is defined at whole-repeat displacements. A one-repeat contraction
    is modeled as 40% of the parent peak and compounds at larger negative
    offsets. Expansion stutter begins at 10% and compounds in the same way.
    """
    if offset == 0:
        return 1.0
    if not float(offset).is_integer():
        return 0.0
    offset = int(offset)
    if offset < 0:
        return params.backward_stutter ** abs(offset)
    return params.forward_stutter ** offset


def remove_stutter(
    observed_reads: int,
    parent_reads: int,
    offset: float,
    params: CallerParameters,
) -> int:
    """Subtract the expected contribution from one parent allele."""
    expected = parent_reads * stutter_fraction(offset, params)
    return max(int(round(observed_reads - expected)), 0)


def collapse_peaks(
    locus_reads: pd.DataFrame,
    allele_map: Mapping[int, str],
) -> list[Peak]:
    """Collapse repeated observations and retain peaks with known allele codes."""
    grouped = (
        locus_reads.assign(
            total_reads=locus_reads["forward_reads"] + locus_reads["reverse_reads"]
        )
        .query("total_reads > 0 and repeat != 0")
        .groupby("repeat", sort=True)["total_reads"]
        .sum()
        .sort_values(ascending=False)
    )

    peaks: list[Peak] = []
    for repeat, reads in grouped.items():
        allele = allele_map.get(int(repeat), "")
        if allele:
            peaks.append(Peak(float(repeat), int(reads), allele))
    return peaks


def _first_pass(
    peaks: Iterable[Peak],
    primary: Peak,
    params: CallerParameters,
) -> list[CorrectedPeak]:
    """Remove stutter generated by the dominant peak."""
    corrected: list[CorrectedPeak] = []
    for peak in peaks:
        offset = round(peak.repeat - primary.repeat)
        reads = (
            peak.reads
            if offset == 0
            else remove_stutter(peak.reads, primary.reads, offset, params)
        )
        corrected.append(
            CorrectedPeak(
                repeat=peak.repeat,
                allele=peak.allele,
                raw_reads=peak.reads,
                corrected_reads=reads,
            )
        )
    return corrected


def _choose_secondary(
    peaks: Iterable[CorrectedPeak],
    primary: Peak,
    params: CallerParameters,
) -> CorrectedPeak | None:
    """Return the strongest residual peak that clears the evidence thresholds."""
    candidates: list[CorrectedPeak] = []

    for peak in peaks:
        offset = round(peak.repeat - primary.repeat)
        if offset == 0:
            continue

        minimum = params.candidate_fraction(offset) * primary.reads
        if peak.corrected_reads < minimum:
            continue
        if peak.corrected_reads < params.min_allele_reads:
            continue
        candidates.append(peak)

    return max(candidates, key=lambda peak: peak.corrected_reads, default=None)


def _second_pass(
    peaks: Iterable[CorrectedPeak],
    secondary: CorrectedPeak,
    params: CallerParameters,
) -> list[CorrectedPeak]:
    """Remove residual stutter attributable to an accepted second allele."""
    updated: list[CorrectedPeak] = []

    for peak in peaks:
        offset = peak.repeat - secondary.repeat
        reads = (
            peak.corrected_reads
            if offset == 0
            else remove_stutter(
                peak.corrected_reads,
                secondary.corrected_reads,
                offset,
                params,
            )
        )
        updated.append(
            CorrectedPeak(
                repeat=peak.repeat,
                allele=peak.allele,
                raw_reads=peak.raw_reads,
                corrected_reads=reads,
                selected=peak.repeat in {secondary.repeat},
            )
        )
    return updated


def call_locus(
    locus: str,
    locus_reads: pd.DataFrame,
    allele_map: Mapping[int, str],
    params: CallerParameters = CallerParameters(),
) -> tuple[GenotypeCall, pd.DataFrame]:
    """Call a diploid STR genotype for one locus.

    Returns both the locus-level result and a peak-level audit table so every
    call can be traced back to the signal used to make it.
    """
    peaks = collapse_peaks(locus_reads, allele_map)
    raw_depth = sum(peak.reads for peak in peaks)

    if not peaks:
        return _no_call(locus, "NO_MAPPED_SIGNAL"), pd.DataFrame()

    primary = max(peaks, key=lambda peak: peak.reads)
    corrected = _first_pass(peaks, primary, params)

    if raw_depth < params.min_locus_reads:
        return (
            _no_call(locus, "LOW_DEPTH", raw_depth=raw_depth),
            _audit_table(corrected, primary.repeat, None),
        )

    secondary = _choose_secondary(corrected, primary, params)
    if secondary is not None:
        corrected = _second_pass(corrected, secondary, params)

    corrected_depth = sum(peak.corrected_reads for peak in corrected)
    primary_reads = next(
        peak.corrected_reads for peak in corrected if peak.repeat == primary.repeat
    )
    secondary_reads = secondary.corrected_reads if secondary is not None else 0

    explained_reads = primary_reads + secondary_reads
    confidence = (
        round(explained_reads / corrected_depth, 2) * 100
        if corrected_depth
        else 0.0
    )

    second_allele = secondary.allele if secondary is not None else primary.allele
    genotype = "/".join(sorted((primary.allele, second_allele)))
    status = "PASS"

    if confidence < params.min_confidence:
        genotype = f"NoCall({genotype})"
        status = "LOW_CONFIDENCE"

    call = GenotypeCall(
        locus=locus,
        genotype=genotype,
        confidence=confidence,
        status=status,
        primary_repeat=primary.repeat,
        secondary_repeat=secondary.repeat if secondary is not None else None,
        raw_depth=raw_depth,
        corrected_depth=corrected_depth,
    )
    return call, _audit_table(corrected, primary.repeat, call.secondary_repeat)


def call_panel(
    reads: pd.DataFrame,
    allele_maps: Mapping[str, Mapping[int, str]],
    params: CallerParameters = CallerParameters(),
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Call every requested locus in a read-count table."""
    required = {"locus", "repeat", "forward_reads", "reverse_reads"}
    missing = required - set(reads.columns)
    if missing:
        raise ValueError(f"Missing read columns: {', '.join(sorted(missing))}")

    calls: list[dict[str, object]] = []
    audits: list[pd.DataFrame] = []

    grouped_reads = {locus: frame for locus, frame in reads.groupby("locus")}
    empty = reads.iloc[:0]

    for locus, allele_map in allele_maps.items():
        call, audit = call_locus(
            locus,
            grouped_reads.get(locus, empty),
            allele_map,
            params,
        )
        calls.append(call.__dict__ if hasattr(call, "__dict__") else {
            field: getattr(call, field) for field in call.__dataclass_fields__
        })
        if not audit.empty:
            audit.insert(0, "locus", locus)
            audits.append(audit)

    return pd.DataFrame(calls), pd.concat(audits, ignore_index=True) if audits else pd.DataFrame()


def _audit_table(
    peaks: Iterable[CorrectedPeak],
    primary_repeat: float,
    secondary_repeat: float | None,
) -> pd.DataFrame:
    rows = []
    for peak in peaks:
        rows.append(
            {
                "repeat": peak.repeat,
                "allele": peak.allele,
                "raw_reads": peak.raw_reads,
                "corrected_reads": peak.corrected_reads,
                "selected": peak.repeat == primary_repeat
                or peak.repeat == secondary_repeat,
            }
        )
    return pd.DataFrame(rows).sort_values("repeat").reset_index(drop=True)


def _no_call(
    locus: str,
    status: str,
    *,
    raw_depth: int = 0,
) -> GenotypeCall:
    return GenotypeCall(
        locus=locus,
        genotype="NoCall",
        confidence=0.0,
        status=status,
        primary_repeat=None,
        secondary_repeat=None,
        raw_depth=raw_depth,
        corrected_depth=0,
    )


def load_allele_maps(path: str | Path) -> dict[str, dict[int, str]]:
    """Load a long-form TSV with columns: locus, repeat, allele."""
    frame = pd.read_csv(path, sep="\t")
    required = {"locus", "repeat", "allele"}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"Missing allele-map columns: {', '.join(sorted(missing))}")

    maps: dict[str, dict[int, str]] = {}
    for locus, group in frame.groupby("locus"):
        maps[str(locus)] = {
            int(row.repeat): str(row.allele)
            for row in group.itertuples(index=False)
            if pd.notna(row.allele)
        }
    return maps


def main() -> None:
    parser = argparse.ArgumentParser(description="Call STR genotypes from read-count peaks")
    parser.add_argument("--reads", required=True, help="TSV containing locus/repeat/read counts")
    parser.add_argument("--alleles", required=True, help="TSV containing locus/repeat/allele mapping")
    parser.add_argument("--calls", required=True, help="Output TSV for genotype calls")
    parser.add_argument("--audit", required=True, help="Output TSV for corrected peak data")
    args = parser.parse_args()

    reads = pd.read_csv(args.reads, sep="\t")
    allele_maps = load_allele_maps(args.alleles)
    calls, audit = call_panel(reads, allele_maps)
    calls.to_csv(args.calls, sep="\t", index=False)
    audit.to_csv(args.audit, sep="\t", index=False)


if __name__ == "__main__":
    main()